version: '3'
services:
    web:
        image: nginx:latest
        container_name: ascio-framework-web
        ports:
            - "8000:80"
        volumes:
            - ..:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php            
            - mysql:db   
        env_file:
        - ../.env
        restart: always
        depends_on:
        - php         
    php:
        build:
            context: .
        image: ascio-framework
        container_name: ascio-framework-php
        volumes:
            - ..:/code
        env_file:
        - ../.env
        environment: 
        - config=cvkd148
        restart: always
        depends_on: 
        - mysql
        - kafka
    poll-cvkd148:
        build:
            context: .
        image: ascio-framework
        container_name: ascio-framework-poll-cvkd148
        env_file:
        - ../.env
        restart: always
        volumes:
            - ..:/code
        depends_on: 
        - mysql
        - kafka
        environment: 
        - config=cvkd148
        entrypoint: /usr/local/bin/php 
        command: services/poll.php
    poll-webrender2:
        build:
            context: .
        image: ascio-framework
        container_name: ascio-framework-poll-webrender2
        env_file:
        - ../.env
        restart: always
        volumes:
            - ..:/code
        depends_on: 
        - mysql
        - kafka
        environment: 
        - config=webrender2
        entrypoint: /usr/local/bin/php 
        command: services/poll.php
    poll-ml:
        build:
            context: .
        image: ascio-framework
        container_name: ascio-framework-poll-ml
        env_file:
        - ../.env
        restart: always
        volumes:
            - ..:/code
        depends_on: 
        - mysql
        - kafka
        environment: 
        - config=mlautenschlager
        entrypoint: /usr/local/bin/php 
        command: services/poll.php
    poll-webrender:
        build:
            context: .
        image: ascio-framework
        container_name: ascio-framework-poll-webrender
        env_file:
        - ../.env
        restart: always
        volumes:
            - ..:/code
        depends_on: 
        - mysql
        - kafka
        environment: 
        - config=webrender
        entrypoint: /usr/local/bin/php 
        command: services/poll.php
    sync:
        build:
            context: .
        image: ascio-framework
        container_name: ascio-framework-sync
        volumes:
            - ..:/code
        env_file:
        - ../.env
        restart: always
        depends_on: 
        - mysql-connector
        - kafka
        entrypoint: /usr/local/bin/php 
        command: services/sync.php
    order-queue:
        build:
            context: .
        image: ascio-framework
        container_name: ascio-framework-order-queue
        volumes:
            - ..:/code
        env_file:
        - ../.env
        restart: always
        depends_on: 
        - mysql-connector
        - kafka
        entrypoint: /usr/local/bin/php 
        command: services/order-queue.php
    
    mysql-connector:
        build:
            context: .
        image: ascio-framework
        container_name: ascio-framework-mysql-connector
        env_file:
        - ../.env
        volumes:
            - ..:/code
        restart: always
        depends_on: 
        - mysql
        - kafka
        entrypoint: /usr/local/bin/php 
        command: services/mysql-connector.php                
    mysql:
        image: mysql:5.7
        container_name: ascio-framework-mysql
        ports:
        - 13307:3306
        env_file:
        - ../.env
        restart: always
        volumes:
        - ascio-framework-volume:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ascio-framework-pma
        env_file:
            - ../.env
        restart: always
        ports:
        - 8001:80
        volumes:
        - /sessions      
        links:
            - mysql:db 
        depends_on: 
        - mysql
    zookeeper:
        image: wurstmeister/zookeeper
        container_name: ascio-framework-zookeeper
        restart: always 
        ports:
        - 2181:2181

    kafka:
        image: wurstmeister/kafka
        container_name: ascio-framework-kafka
        restart: always 
        ports:
        - 9092:9092
        env_file:
        - ../.env
        environment:
            KAFKA_CREATE_TOPICS: "ascio.api.framework.object.full:1:1,ascio.api.framework.object.incremental:1:1,ascio.api.framework.callback:1:1,ascio.api.framework.order:1:1,ascio.api.framework.log:1:1"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
        - zookeeper

volumes:
    ascio-framework-volume:
